### ISSUE TITLE
A Closer Look at Few-shot Image Generation.

### ISSUE THREAD

**Issue by gouayao** [yunqing-me/AdAM#1]
Dear Zhao,

My name is gouayao, and I am a doctoral candidate. First, thank you very much for your outstanding work on ‘A Closer Look at Few-shot Image Generation.’ I reproduced the implementation of this paper. However, compared with the original experimental results, I got slightly worse experimental results. I suspect I missed some crucial points in the reproduction process. I would appreciate it if you could provide me with some key codes. Thank you again for your excellent work.
With kind regards,
gouayao

**Comment by yunqing-me** [comment]
Hi, please refer to the future update of the paper and the project page will be updated. 

Thanks
