### ISSUE TITLE
Num batch fisher and noise fisher

### ISSUE THREAD

**Issue by aminullah6264** [yunqing-me/AdAM#3]
Could you please explain the two loops? 

if fisher_idx is greater than the batch size it gives out of index error. 

https://github.com/yunqing-me/AdAM/blob/68dd0fa0b7b97e730dcf43d5f09ebd70f0a86c61/AdAM_importance_probing.py#L194

**Comment by yunqing-me** [comment]
Thank you for your interest in our work.

- During the importance probing stage, we only evaluate the fisher information once after `500` iterations, see the bash script [here](https://github.com/yunqing-me/AdAM/blob/68dd0fa0b7b97e730dcf43d5f09ebd70f0a86c61/_bash_importance_probing.sh#LL13C22-L13C33). You may ignore the initial evaluation when `i==0` in [this line](https://github.com/yunqing-me/AdAM/blob/68dd0fa0b7b97e730dcf43d5f09ebd70f0a86c61/AdAM_importance_probing.py#L181).
- We use `1000` randomly generated noise as input to compute the fisher information (`args.num_batch_fisher=250` and `args.batch=4`). 
- Therefore, you may need to generate `1000` noise first. We will update the code to generate the noise input.

Thanks,

**Comment by yunqing-me** [comment]
Thank you for your comments, the code is updated (noise generation, importance probing, etc.)
