### ISSUE TITLE
Can't reproduce the FID of some experiments

### ISSUE THREAD

**Issue by LarryHYQ** [yunqing-me/AdAM#4]
I utilized your code to replicate the experiments and also used other target datasets you provided for experiments. Among these datasets, the FID scores for the babies, sunglasses, metfaces, and afhq-cat experiments aligned well with the values stated in the paper. However, there is a notable disparity in the FID scores for the afhq-dog and afhq-wild experiments, which stand at 121.44 and 45.19, respectively. These values significantly diverge from the values reported in the paper. Additionally, during the latter stages of training for these two target domains, specifically after approximately 1200 iterations, a distinct overfitting pattern became evident.

Could you kindly furnish the specific details regarding your training process? Such information would greatly aid in my efforts to meticulously replicate the experiment.

I sincerely appreciate your assistance.

**Comment by yunqing-me** [comment]
Thank you for your interest in our work. 

Could you please let me know the experiment setup (args) you used for AFHQ-Dog and AFHQ-Wild?
